### PR TITLE
Remove B_parameter

### PR DESCRIPTION
**Pull request by danilomendesdias**
This parameter is no longer required as we are dropping support for the respective method on PVT side

(RFDAP-2502)

### CODE REVIEW

**Review by nicoddemus — CHANGES_REQUESTED** [review]
Please update the CHANGELOG as well.

**Comment by danilomendesdias** [comment]
> Please update the CHANGELOG as well.

would be this a 0.9.0?

**Comment by danilomendesdias** [comment]
> > Please update the CHANGELOG as well.
> 
> would be this a version 0.9.0?

Oh, the 0.8.0 is not published yet, so maybe I don't need to change that, right?

**Review by williamjamir — APPROVED** [review]
Awesome!
Thank you for taking the time to update this for us xD! 

I would normally comment that we need to keep backward compatibility, but this property is really particular; therefore we can drop it without weighing on our conscience 🙃

**Comment by nicoddemus** [comment]
@williamjamir do we have some version _in the file format_ that we need to update?

**Comment by williamjamir** [comment]
> @williamjamir do we have some version _in the file format_ that we need to update?
We have a file `version.py` on `alfasim_sdk.src._alfasim_sdk`, but this PR doesn't need to update that file because is already on `v0.8.0` (unreleased) and the last version at PyPI is `v0.7.0`

**Comment by danilomendesdias** [comment]
ping @nicoddemus

**Review by nicoddemus — APPROVED** [review]

**Pull request merged**
