### PR TITLE
[alfasim] Reintegrate version 23.2.0 into master

### PR DESCRIPTION
**Pull request by ro-oliveira95**
Explaining this mess:
- https://github.com/ESSS/alfasim-sdk/pull/354/commits/d37eeb1427ae1a833fca07a7bbd312cbacb10e99 ("Add new field...") is already on master. It was cherry-picked from there because branch `rb-ASIM-v23.2.0` was created after its merge on master.
- https://github.com/ESSS/alfasim-sdk/pull/354/commits/3095bac7b398602dec59b1a3f968ead6adf07106 ("Bump to version 0.20.0") has two "UNRELEASED" sessions because the 1.19.0 was fulfilled in 23d653199323c86cbe47808e94d7507b1c943f9c (I have separated the changes in two commits, which ended up being a bad choice, see next bullets)
- https://github.com/ESSS/alfasim-sdk/pull/354/commits/32e324e134a91a72e0288d79ed806d83c888d590 ("Add release date...") and the following merge commit are here as a try to resolve the conflict in the `CHANGELOG.rst` file, which ended up not resolving the conflict (not clear to me why...)
- https://github.com/ESSS/alfasim-sdk/pull/354/commits/52056c4c7dfdd1ec7437e5e899132ad450689cc0 ("Merge master into...") is here to actually solve the conflict

### CODE REVIEW

**Review by BeneBr — APPROVED** [review]

**Review by nicoddemus — APPROVED** [review]

**Comment by nicoddemus** [comment]
A mess indeed, but that happens.

**Comment by prusse-martin** [comment]
> https://github.com/ESSS/alfasim-sdk/commit/d37eeb1427ae1a833fca07a7bbd312cbacb10e99 ("Add new field...") is already on master. It was cherry-picked from there because branch rb-ASIM-v23.2.0 was created after its merge on master.

The change log entry for this should be moved since it was not really released in 0.19.0 (move it up to the unreleased 0.20.0).

**Comment by ro-oliveira95** [comment]
Closing this in favor of #356.

**Comment by ro-oliveira95** [comment]
> > [d37eeb1](https://github.com/ESSS/alfasim-sdk/commit/d37eeb1427ae1a833fca07a7bbd312cbacb10e99) ("Add new field...") is already on master. It was cherry-picked from there because branch rb-ASIM-v23.2.0 was created after its merge on master.
> 
> The change log entry for this should be moved since it was not really released in 0.19.0 (move it up to the unreleased 0.20.0).
> 
> Or I did get the text wrong? and it was on the actual 0.19.0 release?

Those changes entered in the released 0.19.0, so I guess the changelog is right. 
Sorry for the confusions.

**Pull request closed without merging**
