### PR TITLE
(ASIM-4648) Add alfacase support for black-oil properties

### PR DESCRIPTION
**Pull request by dettmerramon**

### CODE REVIEW

**Comment by prusse-martin** [comment]
There are changes that will affect generated code (the schema and documentaton).

**Review by prusse-martin — APPROVED** [review]

**Review by nicoddemus — CHANGES_REQUESTED** [review]
LGTM, please update the CHANGELOG with the new properties. 👍

**Comment by prusse-martin** [comment]
Did you change defaults.
Why?

**Comment by dettmerramon** [comment]
> You did change defaults. Why?

Synthetic tests were failing because of it

**Pull request merged**
